### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by khanzadimahdi** [mb-programmer/simple-blog#2]
<div dir="rtl">
داداش فکر نمیکنی با اجرا کردن کوئری به صورت زیر امکان داره اینجکشن بخوری؟ هرچی از کاربر میگیری یکسراست میزاری توی کوئری و ران میکنی؟ 
</div>

```php
$sql = "UPDATE posts SET title='{$post['title']}', body='{$post['body']}', category_id='{$post['category_id']}' WHERE id={$post['id']}";

```

**Comment by mbpcoder** [comment]
سلام.
چرا میتونیم.
 این پروژه جهت شروع برنامه نویسی و یادگیری یه سری مفاهیم پایه است
برای همین سعی کردم این بخش ها رو از کد حذف کنم.
